// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    c360_accounts: {
        name: "c360_accounts";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          account_id: string;
          /** @sqlType STRING */
          account_type: string;
          /** @sqlType STRING */
          status: string;
          /** @sqlType BIGINT */
          balance: number;
          /** @sqlType STRING */
          product_tier: string;
          /** @sqlType STRING */
          branch_region: string;
        }>;
      };
    c360_cards: {
        name: "c360_cards";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          card_id: string;
          /** @sqlType STRING */
          card_type: string;
          /** @sqlType BOOLEAN */
          is_virtual: boolean;
          /** @sqlType STRING */
          status: string;
        }>;
      };
    c360_cases: {
        name: "c360_cases";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          case_id: string;
          /** @sqlType STRING */
          fraud_type: string;
          /** @sqlType STRING */
          opened: string;
          /** @sqlType DOUBLE */
          risk_score: number;
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          disposition: string;
          /** @sqlType STRING */
          assigned_to: string;
        }>;
      };
    c360_events: {
        name: "c360_events";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          event_time: string;
          /** @sqlType STRING */
          event_type: string;
          /** @sqlType STRING */
          device_id: string;
          /** @sqlType STRING */
          os: string;
          /** @sqlType STRING */
          ip_country: string;
        }>;
      };
    c360_loans: {
        name: "c360_loans";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          loan_id: string;
          /** @sqlType STRING */
          product_id: string;
          /** @sqlType BIGINT */
          principal_amount: number;
          /** Remaining principal balance (IDR). */
          outstanding_principal: number;
          /** @sqlType DOUBLE */
          interest_rate_pa: number;
          /** @sqlType BIGINT */
          tenor_months: number;
          /** Loan status: current | paid_off | delinquent | default | written_off. */
          status: string;
          /** Days past due — drives PAR30 / PAR90 and NPL classification. */
          dpd: number;
        }>;
      };
    c360_profile: {
        name: "c360_profile";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_id: string;
          /** @sqlType STRING */
          full_name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          province: string;
          /** @sqlType BIGINT */
          age: number;
          /** @sqlType STRING */
          gender: string;
          /** @sqlType STRING */
          income_band: string;
          /** @sqlType STRING */
          credit_score_band: string;
          /** @sqlType STRING */
          kyc_status: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType INT */
          tenure_days: number;
          /** @sqlType BIGINT */
          txn_90d: number;
          /** @sqlType BIGINT */
          txn_30d: number;
          /** @sqlType BIGINT */
          value_90d: number;
          /** @sqlType BIGINT */
          value_30d: number;
          /** @sqlType INT */
          recency_days: number;
          /** @sqlType BIGINT */
          login_30d: number;
          /** @sqlType BIGINT */
          n_accounts: number;
          /** @sqlType BIGINT */
          total_balance: number;
          /** @sqlType BIGINT */
          n_cards: number;
          /** @sqlType BIGINT */
          n_loans: number;
          /** @sqlType BIGINT */
          loan_outstanding: number;
          /** @sqlType BIGINT */
          max_dpd: number;
          /** @sqlType BIGINT */
          n_fraud_cases: number;
          /** @sqlType BIGINT */
          fraud_txn_90d: number;
          /** @sqlType FLOAT */
          churn_score: number;
          /** @sqlType FLOAT */
          clv_pred_idr: number;
          /** @sqlType STRING */
          next_best_action: string;
          /** @sqlType STRING */
          risk_band: string;
        }>;
      };
    gov_pii: {
        name: "gov_pii";
        parameters: {
          /** STRING - use sql.string() */
          can_unmask: SQLStringMarker;
          /** STRING - use sql.string() */
          region_scope: SQLStringMarker;
        };
        result: Array<{
          /** Unique customer identifier (PK). */
          customer_id: string;
          /** @sqlType STRING */
          full_name: string;
          /** @sqlType STRING */
          nik: string;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          region: string;
          /** KYC verification state: Verified / Pending / Rejected. */
          kyc_status: string;
        }>;
      };
    gov_summary: {
        name: "gov_summary";
        parameters: {
          /** STRING - use sql.string() */
          can_unmask: SQLStringMarker;
          /** STRING - use sql.string() */
          region_scope: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          pii_visible: string;
          /** @sqlType STRING */
          region_scope: string;
          /** @sqlType BIGINT */
          visible_customers: number;
          /** @sqlType BIGINT */
          visible_regions: number;
        }>;
      };
    gov_txn_by_region: {
        name: "gov_txn_by_region";
        parameters: {
          /** STRING - use sql.string() */
          region_scope: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          region: string;
          /** @sqlType BIGINT */
          customers: number;
        }>;
      };
    ops_deposits_by_region: {
        name: "ops_deposits_by_region";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          region: string;
          /** @sqlType DOUBLE */
          deposits_bn_idr: number;
          /** @sqlType BIGINT */
          accounts: number;
        }>;
      };
    ops_deposits_by_tier: {
        name: "ops_deposits_by_tier";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          tier: string;
          /** @sqlType DOUBLE */
          deposits_bn_idr: number;
        }>;
      };
    ops_fraud_trend: {
        name: "ops_fraud_trend";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          day: string;
          /** @sqlType BIGINT */
          txns: number;
          /** @sqlType BIGINT */
          fraud_txns: number;
          /** @sqlType DOUBLE */
          fraud_rate_pct: number;
        }>;
      };
    ops_kpis: {
        name: "ops_kpis";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          customers: number;
          /** @sqlType DOUBLE */
          deposits_tn_idr: number;
          /** @sqlType DOUBLE */
          loans_out_bn_idr: number;
          /** @sqlType DOUBLE */
          avg_churn: number;
          /** @sqlType BIGINT */
          fraud_txns_30d: number;
          /** @sqlType DOUBLE */
          fraud_rate_30d: number;
        }>;
      };
    ops_loans_by_status: {
        name: "ops_loans_by_status";
        parameters: Record<string, never>;
        result: Array<{
          /** Loan status: current | paid_off | delinquent | default | written_off. */
          status: string;
          /** @sqlType BIGINT */
          loans: number;
          /** @sqlType DOUBLE */
          outstanding_bn_idr: number;
        }>;
      };
    ops_txn_by_channel: {
        name: "ops_txn_by_channel";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          channel: string;
          /** @sqlType BIGINT */
          txns: number;
        }>;
      };
    txn_stream: {
        name: "txn_stream";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          txn_id: string;
          /** Unique customer identifier (PK). */
          customer_id: string;
          /** @sqlType STRING */
          channel: string;
          /** @sqlType STRING */
          txn_time: string;
          /** @sqlType BIGINT */
          amount: number;
          /** @sqlType STRING */
          direction: string;
          /** @sqlType STRING */
          status: string;
          /** @sqlType BOOLEAN */
          is_fraud: boolean;
          /** @sqlType BOOLEAN */
          is_night: boolean;
          /** @sqlType BOOLEAN */
          is_foreign_ip: boolean;
        }>;
      };
    whoami: {
        name: "whoami";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          identity: string;
          /** @sqlType BOOLEAN */
          is_ws_admin: boolean;
        }>;
      };
  }
}
